// Generated by gencpp from file heatmap/signal_serviceResponse.msg
// DO NOT EDIT!


#ifndef HEATMAP_MESSAGE_SIGNAL_SERVICERESPONSE_H
#define HEATMAP_MESSAGE_SIGNAL_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <heatmap/wifi_signal.h>

namespace heatmap
{
template <class ContainerAllocator>
struct signal_serviceResponse_
{
  typedef signal_serviceResponse_<ContainerAllocator> Type;

  signal_serviceResponse_()
    : signal()  {
    }
  signal_serviceResponse_(const ContainerAllocator& _alloc)
    : signal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::heatmap::wifi_signal_<ContainerAllocator>  _signal_type;
  _signal_type signal;





  typedef boost::shared_ptr< ::heatmap::signal_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heatmap::signal_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct signal_serviceResponse_

typedef ::heatmap::signal_serviceResponse_<std::allocator<void> > signal_serviceResponse;

typedef boost::shared_ptr< ::heatmap::signal_serviceResponse > signal_serviceResponsePtr;
typedef boost::shared_ptr< ::heatmap::signal_serviceResponse const> signal_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heatmap::signal_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heatmap::signal_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::heatmap::signal_serviceResponse_<ContainerAllocator1> & lhs, const ::heatmap::signal_serviceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.signal == rhs.signal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::heatmap::signal_serviceResponse_<ContainerAllocator1> & lhs, const ::heatmap::signal_serviceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace heatmap

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::heatmap::signal_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heatmap::signal_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heatmap::signal_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heatmap::signal_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap::signal_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap::signal_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heatmap::signal_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58da7ff476f57ac5f5a609923bf16293";
  }

  static const char* value(const ::heatmap::signal_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58da7ff476f57ac5ULL;
  static const uint64_t static_value2 = 0xf5a609923bf16293ULL;
};

template<class ContainerAllocator>
struct DataType< ::heatmap::signal_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heatmap/signal_serviceResponse";
  }

  static const char* value(const ::heatmap::signal_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heatmap::signal_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "wifi_signal signal\n"
"\n"
"================================================================================\n"
"MSG: heatmap/wifi_signal\n"
"string essid\n"
"uint8 link_quality\n"
"uint8 link_quality_max\n"
"int32 bitrate\n"
;
  }

  static const char* value(const ::heatmap::signal_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heatmap::signal_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.signal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct signal_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heatmap::signal_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::heatmap::signal_serviceResponse_<ContainerAllocator>& v)
  {
    s << indent << "signal: ";
    s << std::endl;
    Printer< ::heatmap::wifi_signal_<ContainerAllocator> >::stream(s, indent + "  ", v.signal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEATMAP_MESSAGE_SIGNAL_SERVICERESPONSE_H
