// Generated by gencpp from file heatmap/signal_serviceRequest.msg
// DO NOT EDIT!


#ifndef HEATMAP_MESSAGE_SIGNAL_SERVICEREQUEST_H
#define HEATMAP_MESSAGE_SIGNAL_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace heatmap
{
template <class ContainerAllocator>
struct signal_serviceRequest_
{
  typedef signal_serviceRequest_<ContainerAllocator> Type;

  signal_serviceRequest_()
    {
    }
  signal_serviceRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::heatmap::signal_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::heatmap::signal_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct signal_serviceRequest_

typedef ::heatmap::signal_serviceRequest_<std::allocator<void> > signal_serviceRequest;

typedef boost::shared_ptr< ::heatmap::signal_serviceRequest > signal_serviceRequestPtr;
typedef boost::shared_ptr< ::heatmap::signal_serviceRequest const> signal_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::heatmap::signal_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::heatmap::signal_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace heatmap

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::heatmap::signal_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::heatmap::signal_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heatmap::signal_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::heatmap::signal_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap::signal_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::heatmap::signal_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::heatmap::signal_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::heatmap::signal_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::heatmap::signal_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "heatmap/signal_serviceRequest";
  }

  static const char* value(const ::heatmap::signal_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::heatmap::signal_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::heatmap::signal_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::heatmap::signal_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct signal_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::heatmap::signal_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::heatmap::signal_serviceRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // HEATMAP_MESSAGE_SIGNAL_SERVICEREQUEST_H
