// Generated by gencpp from file ros_basics_tutorials/AddThreeIntsRequest.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_TUTORIALS_MESSAGE_ADDTHREEINTSREQUEST_H
#define ROS_BASICS_TUTORIALS_MESSAGE_ADDTHREEINTSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_basics_tutorials
{
template <class ContainerAllocator>
struct AddThreeIntsRequest_
{
  typedef AddThreeIntsRequest_<ContainerAllocator> Type;

  AddThreeIntsRequest_()
    : a(0)
    , b(0)
    , c(0)  {
    }
  AddThreeIntsRequest_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)
    , c(0)  {
  (void)_alloc;
    }



   typedef int64_t _a_type;
  _a_type a;

   typedef int64_t _b_type;
  _b_type b;

   typedef int64_t _c_type;
  _c_type c;





  typedef boost::shared_ptr< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AddThreeIntsRequest_

typedef ::ros_basics_tutorials::AddThreeIntsRequest_<std::allocator<void> > AddThreeIntsRequest;

typedef boost::shared_ptr< ::ros_basics_tutorials::AddThreeIntsRequest > AddThreeIntsRequestPtr;
typedef boost::shared_ptr< ::ros_basics_tutorials::AddThreeIntsRequest const> AddThreeIntsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator1> & lhs, const ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator1> & lhs, const ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_basics_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8559b52d432bccd240703f31aeca517";
  }

  static const char* value(const ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8559b52d432bccdULL;
  static const uint64_t static_value2 = 0x240703f31aeca517ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_basics_tutorials/AddThreeIntsRequest";
  }

  static const char* value(const ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 a\n"
"int64 b\n"
"int64 c\n"
;
  }

  static const char* value(const ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AddThreeIntsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_basics_tutorials::AddThreeIntsRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int64_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int64_t>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<int64_t>::stream(s, indent + "  ", v.c);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASICS_TUTORIALS_MESSAGE_ADDTHREEINTSREQUEST_H
