// Generated by gencpp from file ros_basics_tutorials/IoT_Sensor.msg
// DO NOT EDIT!


#ifndef ROS_BASICS_TUTORIALS_MESSAGE_IOT_SENSOR_H
#define ROS_BASICS_TUTORIALS_MESSAGE_IOT_SENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_basics_tutorials
{
template <class ContainerAllocator>
struct IoT_Sensor_
{
  typedef IoT_Sensor_<ContainerAllocator> Type;

  IoT_Sensor_()
    : id(0)
    , name()
    , temperature(0.0)
    , humidity(0.0)
    , altitude(0.0)  {
    }
  IoT_Sensor_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)
    , temperature(0.0)
    , humidity(0.0)
    , altitude(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef float _temperature_type;
  _temperature_type temperature;

   typedef float _humidity_type;
  _humidity_type humidity;

   typedef float _altitude_type;
  _altitude_type altitude;





  typedef boost::shared_ptr< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> const> ConstPtr;

}; // struct IoT_Sensor_

typedef ::ros_basics_tutorials::IoT_Sensor_<std::allocator<void> > IoT_Sensor;

typedef boost::shared_ptr< ::ros_basics_tutorials::IoT_Sensor > IoT_SensorPtr;
typedef boost::shared_ptr< ::ros_basics_tutorials::IoT_Sensor const> IoT_SensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator1> & lhs, const ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.temperature == rhs.temperature &&
    lhs.humidity == rhs.humidity &&
    lhs.altitude == rhs.altitude;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator1> & lhs, const ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_basics_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef2910c9e296f58e286403167297de66";
  }

  static const char* value(const ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef2910c9e296f58eULL;
  static const uint64_t static_value2 = 0x286403167297de66ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_basics_tutorials/IoT_Sensor";
  }

  static const char* value(const ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string name\n"
"float32 temperature\n"
"float32 humidity\n"
"float32 altitude\n"
;
  }

  static const char* value(const ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.temperature);
      stream.next(m.humidity);
      stream.next(m.altitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct IoT_Sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_basics_tutorials::IoT_Sensor_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "temperature: ";
    Printer<float>::stream(s, indent + "  ", v.temperature);
    s << indent << "humidity: ";
    Printer<float>::stream(s, indent + "  ", v.humidity);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_BASICS_TUTORIALS_MESSAGE_IOT_SENSOR_H
